#!/bin/bash
# install_dashboards — set up the Kalshi dashboards on THIS computer, whatever it is.
#
# The original runner scripts + plists hardcoded one machine's paths
# (/Users/jesse/Desktop/projects/polybot + anaconda). This installer is
# SELF-LOCATING: it derives PROJECT_ROOT from its own location, finds a python,
# and generates fresh runners + LaunchAgents for this machine. Idempotent —
# re-run any time; it unloads/reloads with current paths.
#
#   bash scripts/launchd/install_dashboards.sh            # macOS: always-on LaunchAgents
#   bash scripts/launchd/install_dashboards.sh --serve    # any OS: run both in foreground
#
# Dashboards:
#   crypto  (15-min sleeve)  -> http://127.0.0.1:5053
#   weather (temp sleeve)    -> http://127.0.0.1:5054
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# find a python: prefer anaconda if present (the original setup), else PATH python3
if [ -x "$HOME/anaconda3/bin/python" ]; then
  PY="$HOME/anaconda3/bin/python"
else
  PY="$(command -v python3 || command -v python)"
fi
[ -n "$PY" ] || { echo "no python found on PATH"; exit 1; }

echo "PROJECT_ROOT=$PROJECT_ROOT"
echo "python=$PY"
mkdir -p "$PROJECT_ROOT/logs"

# new-computer gotcha found during smoke test: deps missing -> dashboard exits at boot.
# Verify imports; install from requirements.txt only if something's absent.
if ! "$PY" -c "import flask, dotenv, requests, yaml" 2>/dev/null; then
  echo "installing python deps (first run on this machine) ..."
  "$PY" -m pip install -q -r "$PROJECT_ROOT/requirements.txt"
fi

serve_one() {  # serve_one <main-arg> <port>
  cd "$PROJECT_ROOT"
  if [ -f "$PROJECT_ROOT/.env" ]; then set -a; . "$PROJECT_ROOT/.env"; set +a; fi
  exec "$PY" main.py "$1" --port="$2"
}

if [ "${1:-}" = "--serve" ]; then
  # portable mode: crypto in background, weather in foreground (ctrl-c stops both)
  cd "$PROJECT_ROOT"
  if [ -f "$PROJECT_ROOT/.env" ]; then set -a; . "$PROJECT_ROOT/.env"; set +a; fi
  "$PY" main.py kalshi-dashboard --port=5053 >> "$PROJECT_ROOT/logs/dash_crypto.log" 2>&1 &
  CRYPTO_PID=$!
  trap 'kill $CRYPTO_PID 2>/dev/null || true' EXIT
  echo "crypto  -> http://127.0.0.1:5053  (pid $CRYPTO_PID, log logs/dash_crypto.log)"
  echo "weather -> http://127.0.0.1:5054  (foreground — ctrl-c stops both)"
  exec "$PY" main.py kalshi-weather-dashboard --port=5054
fi

# ── macOS launchd mode ───────────────────────────────────────────────────────
if ! command -v launchctl >/dev/null 2>&1; then
  echo "launchctl not found (not macOS). Use:  bash $0 --serve"
  exit 1
fi
AGENTS="$HOME/Library/LaunchAgents"
mkdir -p "$AGENTS"

gen_runner() {  # gen_runner <name> <main-arg> <port>
  local runner="$PROJECT_ROOT/scripts/launchd/gen_run_$1.sh"
  cat > "$runner" <<EOF
#!/bin/bash
# GENERATED by install_dashboards.sh for this machine — do not hand-edit; re-run installer.
set -euo pipefail
export PATH="$(dirname "$PY"):\$PATH"
PROJECT_ROOT="$PROJECT_ROOT"
cd "\$PROJECT_ROOT"
if [ -f "\$PROJECT_ROOT/.env" ]; then set -a; . "\$PROJECT_ROOT/.env"; set +a; fi
mkdir -p "\$PROJECT_ROOT/logs"
exec "$PY" main.py $2 --port=$3
EOF
  chmod +x "$runner"
  echo "$runner"
}

install_agent() {  # install_agent <label-suffix> <runner-path>
  local label="com.polybot.dash.$1"
  local plist="$AGENTS/$label.plist"
  cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>$2</string></array>
  <key>KeepAlive</key><true/>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>$PROJECT_ROOT/logs/launchd_dash_$1.log</string>
  <key>StandardErrorPath</key><string>$PROJECT_ROOT/logs/launchd_dash_$1_err.log</string>
</dict></plist>
EOF
  launchctl unload "$plist" 2>/dev/null || true
  launchctl load "$plist"
  echo "  installed $label"
}

R1="$(gen_runner crypto kalshi-dashboard 5053)"
R2="$(gen_runner weather kalshi-weather-dashboard 5054)"
install_agent crypto "$R1"
install_agent weather "$R2"

echo ""
echo "Done. Open:"
echo "  crypto  -> http://127.0.0.1:5053"
echo "  weather -> http://127.0.0.1:5054"
echo "Logs: $PROJECT_ROOT/logs/launchd_dash_*.log"
echo "Stop:  launchctl unload ~/Library/LaunchAgents/com.polybot.dash.{crypto,weather}.plist"
